### ISSUE TITLE
categoryID parameter, multiple id problem

### ISSUE THREAD

**Issue by emrepun** [koogawa/FoursquareAPIClient#18]
Hi,

First of all thanks a lot for this repo.

I was checking and trying to implement a project with it but there seems to be a problem when you try to provide multiple ids separating with coma like: "categoryID" : "4xxxxxxx, 4xxxxxx"

It returns back with invalid categoryID response, even though all the categories works perfectly fine alone.

Thanks,
Emre

**Comment by koogawa** [comment]
@emrepun Hi,

Is it possible to remove space?

`"categoryID" : "4xxxxxxx, 4xxxxxx"`
 -> `"categoryID" : "4xxxxxxx,4xxxxxx"`

**Comment by emrepun** [comment]
Hi again,

Last night I've also tried without space and it didn't work. But now I tried again with different IDs and it worked fine, I guess the problem was with one of the IDs I tried yesterday.

Thanks for your answer :)

**Comment by koogawa** [comment]
😀
