### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by whynoceros** [koogawa/FoursquareAPIClient#4]
After tapping the "Connect To Foursquare" button on the login screen, I am receiving an error: "unexpectedly found nil while unwrapping an Optional value" at line 53 FoursquareAuthViewController. This happens in the example app provided. It also happens in my own app, where I am trying to use the Pod, when I call:

let client = FoursquareAuthClient(clientId: clientId, callback: callback, delegate: self)
        client.authorizeWithRootViewController(self)

 Any ideas? Thanks!

![screen shot 2016-08-08 at 11 54 18 pm](https://cloud.githubusercontent.com/assets/1585185/17507239/79fa5974-5dc3-11e6-977d-b4775c3a97fa.png)

**Comment by koogawa** [comment]
Hi whynoceros

Thank you for your report.

Fixed: https://github.com/koogawa/FoursquareAPIClient/commit/3f5372b9f35b975132cb467fa6a329699d60225a

**Comment by koogawa** [comment]
Released https://github.com/koogawa/FoursquareAPIClient/releases/tag/1.0.1
